### ISSUE TITLE
Make all tasks use callbacks rather than code repetition

### ISSUE THREAD

**Issue by nic-barbara** [dazzmo/CassieControllers#14]
When we fixed the bug with task accelerations being positive instead of negative, we found that `joint_track_task.cc` and `joint_limit_task.cc` repeat code from the `Update` function in `task.cc`. They should just have a callback instead.

**Comment by dazzmo** [comment]
The new OSC structure in 5b90119a7c6fc99693b3371f4994a8659659f221 removes the need for callbacks.
